spring:
  application:
    name: vehicle-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/vehicles?serverTimezone=UTC&useUnicode=TRUE&characterEncoding=UTF-8

server:
  port: ${PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}